### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 2,
  "accountNumber": "5371685311",
  "amount":1000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 2,
  "accountNumber": "5371685311",
  "amount":1000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "438d88674d0c4930b14eb1812a8a181e",
  "accountNumber": "5371685311",
  "amount":1000
}

### query transaction
GET http://localhost:8080/transaction/{거래 생성 후 거래 아이디 입력}